set_property SRC_FILE_INFO {cfile:C:/Users/mique/Desktop/TDC-in-Artix-7/TDC_pins.xdc rfile:../../../../TDC_pins.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U19 [get_ports TX]
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T19 [get_ports RX]
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V19 [get_ports CTS]
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W19 [get_ports RTS]
set_property src_info {type:XDC file:1 line:282 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M26 [get_ports led_WriteERR]
set_property src_info {type:XDC file:1 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T24 [get_ports led_ReadERR]
set_property src_info {type:XDC file:1 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T25 [get_ports led_WriteStage]
set_property src_info {type:XDC file:1 line:288 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R26 [get_ports led_ReadStage]
set_property src_info {type:XDC file:1 line:653 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R3 [get_ports clk_p]
set_property src_info {type:XDC file:1 line:654 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P3 [get_ports clk_n]
set_property src_info {type:XDC file:1 line:676 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P6 [get_ports but_startReading]
set_property src_info {type:XDC file:1 line:680 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U5 [get_ports but_startWriting]
set_property src_info {type:XDC file:1 line:686 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R8 [get_ports selector_0]
set_property src_info {type:XDC file:1 line:688 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P8 [get_ports selector_1]
set_property src_info {type:XDC file:1 line:827 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R5 [get_ports but_debugmode]
set_property src_info {type:XDC file:1 line:849 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL BUFG [get_cells u_clk/block_clock_i/clk_wiz_0/inst/clkf_buf]
set_property src_info {type:XDC file:1 line:850 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFGCTRL_X0Y5 [get_cells u_clk/block_clock_i/clk_wiz_0/inst/clkf_buf]
set_property src_info {type:XDC file:1 line:851 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL BUFG [get_cells u_clk/block_clock_i/clk_wiz_0/inst/clkout1_buf]
set_property src_info {type:XDC file:1 line:852 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFGCTRL_X0Y4 [get_cells u_clk/block_clock_i/clk_wiz_0/inst/clkout1_buf]
set_property src_info {type:XDC file:1 line:853 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL BUFG [get_cells uart_clk_BUFG_inst]
set_property src_info {type:XDC file:1 line:854 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFGCTRL_X0Y1 [get_cells uart_clk_BUFG_inst]
set_property src_info {type:XDC file:1 line:855 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL BUFG [get_cells u_clk/block_clock_i/clk_wiz_0/inst/clkout2_buf]
set_property src_info {type:XDC file:1 line:856 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFGCTRL_X0Y0 [get_cells u_clk/block_clock_i/clk_wiz_0/inst/clkout2_buf]
set_property src_info {type:XDC file:1 line:860 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T8 [get_ports hit_p]
set_property src_info {type:XDC file:1 line:861 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T7 [get_ports hit_n]
set_property src_info {type:XDC file:1 line:864 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name uart_clk -source [get_pins u_clk/block_clock_i/clk_wiz_0/inst/plle2_adv_inst/CLKOUT0] -divide_by 64 [get_pins uart_clk_reg/Q]
set_property src_info {type:XDC file:1 line:872 export:INPUT save:INPUT read:READ} [current_design]
create_pblock Pblock_fino
resize_pblock [get_pblocks Pblock_fino] -add {SLICE_X84Y101:SLICE_X87Y198}
set_property EXCLUDE_PLACEMENT 1 [get_pblocks Pblock_fino]
set_property src_info {type:XDC file:1 line:876 export:INPUT save:INPUT read:READ} [current_design]
create_pblock Pblock_decode
add_cells_to_pblock [get_pblocks Pblock_decode] [get_cells -quiet [list u_tdc/u_DecStart u_tdc/u_DecStop]]
resize_pblock [get_pblocks Pblock_decode] -add {SLICE_X88Y109:SLICE_X97Y199}
