# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/mique/Desktop/TDC-in-Artix-7/TDC/TDC_pins.xdc

# Block Designs: bd/block_clock/block_clock.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_clock || ORIG_REF_NAME==block_clock} -quiet] -quiet

# IP: bd/block_clock/ip/block_clock_clk_wiz_0_0/block_clock_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_clock_clk_wiz_0_0 || ORIG_REF_NAME==block_clock_clk_wiz_0_0} -quiet] -quiet

# XDC: c:/Users/mique/Desktop/TDC-in-Artix-7/TDC/Final TDC_StartStop/Final TDC_StartStop.gen/sources_1/bd/block_clock/block_clock_ooc.xdc
